services:
  dev-web:
    image: tudigong-web:dev.${WEB_REF_NAME}.amd64
    env_file: .env.web
    ports:
      - "3001:3000" # 主機的 3001 端口映射到容器的 3000 端口
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=production

  dev-service:
    image: tudigong-service:dev.${SERVICE_REF_NAME}.amd64
    env_file: .env.service
    ports:
      - "8080:8080"
    depends_on:
      dev-db:
        condition: service_healthy

  dev-healthcheck-web-reporter:
    image: alpine:latest
    volumes:
      - ./wait-for-it.sh:/app/wait-for-it.sh
      - ./healthcheck-web.sh:/app/healthcheck-web.sh
    env_file:
      - .env
    command: /bin/sh -c "/app/wait-for-it.sh web:3000 -- /bin/sh /app/healthcheck-web.sh"

  dev-healthcheck-service-reporter:
    image: alpine:latest
    volumes:
      - ./wait-for-it.sh:/app/wait-for-it.sh
      - ./healthcheck-service.sh:/app/healthcheck-service.sh
    env_file:
      - .env
    command: /bin/sh -c "/app/wait-for-it.sh service:8080 -- /bin/sh /app/healthcheck-service.sh"

  dev-db:
    image: mysql:8.0
    env_file: .env.service
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
