services:
  dev-web:
    image: tudigong-web:dev.${REF_NAME}.amd64
    env_file: .env.web
    ports:
      - "3001:3000" # 主機的 3001 端口映射到容器的 3000 端口
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  dev-service:
    image: tudigong-service:dev.${REF_NAME}.amd64
    env_file: .env.service
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  dev-healthcheck-web-reporter:
    image: alpine:latest
    volumes:
      - ./healthcheck-web.sh:/app/healthcheck-web.sh
    env_file:
      - .env
    command: /bin/sh /app/healthcheck-web.sh

  dev-healthcheck-service-reporter:
    image: alpine:latest
    volumes:
      - ./healthcheck-service.sh:/app/healthcheck-service.sh
    env_file:
      - .env
    command: /bin/sh /app/healthcheck-service.sh

  dev-db:
    image: mysql:8.0
    env_file: .env.service
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
