services:
  ci-web:
    env_file: ./.env
    image: tudigong-web:latest.amd64
    ports:
      - "3001:3000"
#   ci-service:
#     env_file: ./.env.service
#     image: tudigong-service:latest.amd64
#     ports:
#       - "8081:8080"
#     depends_on:
#       ci-db:
#         condition: service_healthy
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   ci-db:
#     env_file: ./.env.service
#     image: mysql:8.0
#     volumes:
#       - mysql_data:/var/lib/mysql
#     ports:
#       - "3307:3306"
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       timeout: 20s
#       retries: 10

# volumes:
#   mysql_data:
