services:
  prd-web:
    image: tudigong-web:prd.${WEB_REF_NAME}.amd64
    env_file: .env.web
    ports:
      - "3002:3000" # 主機的 3001 端口映射到容器的 3000 端口
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=production

  prd-service:
    image: tudigong-service:prd.${SERVICE_REF_NAME}.amd64
    env_file: .env.service
    # ports: # 這裡不需要開放 port，因為只有 web 會連 service
    #   - "8082:8080"
    depends_on:
      prd-db:
        condition: service_healthy
    command: /bin/sh /app/entrypoint.sh

  prd-healthcheck-web-reporter:
    image: alpine:latest
    volumes:
      - ./healthcheck-web.sh:/app/healthcheck-web.sh
    env_file:
      - .env
    command: /bin/sh /app/healthcheck-web.sh

  prd-healthcheck-service-reporter:
    image: alpine:latest
    volumes:
      - ./healthcheck-service.sh:/app/healthcheck-service.sh
    env_file:
      - .env
    command: /bin/sh /app/healthcheck-service.sh

  prd-db:
    image: mysql:8.0
    env_file: .env.service
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
